"""
GitHub integration — post commit comments, format reports
"""
import os
from typing import Optional
from github import Github, GithubException
from backend.models.schemas import AnalysisReport, IssueWithSuggestion


def _get_client(token: Optional[str] = None) -> Github:
    token = token or os.getenv("GITHUB_TOKEN", "")
    if not token:
        raise EnvironmentError("GITHUB_TOKEN is not set.")
    return Github(token)


def _format_issue_comment(iws: IssueWithSuggestion) -> str:
    issue = iws.issue
    label_map = {"error": "🔴", "warning": "🟡", "security": "🔒", "dependency": "📦"}
    icon = label_map.get(issue.type, "⚪")
    lines = [
        f"### {icon} `{issue.file}` line {issue.line} [{issue.type.upper()}]",
        f"**Tool:** `{issue.tool}`",
        f"**Message:** {issue.message}",
    ]
    if iws.suggestion:
        s = iws.suggestion
        lines += ["", f"**Explanation:** {s.explanation}", f"**Fix:** {s.fix}"]
        if s.improved_code:
            lines += ["", "**Improved code:**", "```python", s.improved_code, "```"]
    return "\n".join(lines)


def _build_full_comment(report: AnalysisReport) -> str:
    header = (
        f"## 🤖 AI Project Manager — Analysis Report\n\n"
        f"**Repository:** `{report.repository}`  \n"
        f"**Commit:** `{report.commit_id[:8]}`  \n"
        f"**Branch:** `{report.branch}`  \n"
        f"**Severity Score:** `{report.severity_score}/10`  \n"
        f"**Issues Found:** `{len(report.issues)}`\n\n---\n"
    )
    body_parts = [_format_issue_comment(iws) for iws in report.issues[:20]]
    footer = "\n\n---\n*Generated by AI Project Manager*"
    return header + "\n\n".join(body_parts) + footer


def comment_on_commit(report: AnalysisReport, github_token: Optional[str] = None) -> Optional[str]:
    if not report.issues:
        return None
    try:
        g = _get_client(github_token)
        repo = g.get_repo(report.repository)
        commit = repo.get_commit(report.commit_id)
        comment = commit.create_comment(_build_full_comment(report))
        return comment.html_url
    except GithubException as e:
        print(f"[github_service] Failed to comment: {e}")
        return None
